=== chayanunttee/xml/student1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.fitm.kmutnb.ac.th"
	xmlns="http://www.fitm.kmutnb.ac.th" elementFormDefault="qualified">

	<xs:element name="it">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="people" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
								<xs:element name="lname" type="xs:string"/>
								<xs:element name="age" type="xs:integer"/>
							</xs:sequence>
						</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== chayanunttee/xml/student1.xml
<?xml version="1.0" encoding="UTF-8"?>
<it xmlns="http://www.fitm.kmutnb.ac.th"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fitm.kmutnb.ac.th student1.xsd">
	<people>
		<name>aaa</name>
		<lname>bbb</lname>
		<age>17</age>
	</people>
	<people>
		<name>ccc</name>
		<lname>ddd</lname>
		<age>18</age>
	</people>
</it>
